name: QA

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Setup Poetry and dependencies
        run: |
          pip install poetry==1.2.2
          poetry install
      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
